---
- name: stop systemd-resolved.service
  ansible.builtin.service:
    name: systemd-resolved.service
    state: stopped
    enabled: false
- name: update nameserver
  ansible.builtin.copy:
    src: resolv.conf
    dest: /etc/resolv.conf
- name: create a pihole container
  community.docker.docker_container:
    name: pihole
    image: pihole/pihole
    # network_mode: host
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    volumes:
      - "./etc-pihole:/etc/pihole"
      - "./etc-dnsmasq.d:/etc/dnsmasq.d"
    env:
      TZ: "{{ timezone }}"
      WEBPASSWORD: "{{ pihole_web_pw }}"
      PIHOLE_DNS_: "{{ pihole_dns }}"
