---
- name: Setup server
  hosts: localhost
  gather_facts: false
  vars:
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html
    servers:
      - { name: 'my-server-1', type: 'cx11', location: 'fsn1' }
      - { name: 'my-server-2', type: 'cx11', location: 'hel1' }
      - { name: 'my-server-3', type: 'cx11', location: 'nbg1' }
  tasks:
    - name: Create a basic ssh key
      # https://docs.ansible.com/ansible/latest/collections/hetzner/hcloud/ssh_key_module.html#ansible-collections-hetzner-hcloud-ssh-key-module
      hetzner.hcloud.ssh_key:
        name: my-ssh-key
        public_key: "{{ lookup('ansible.builtin.file', '~/.ssh/id_ed25519.pub') }}"
        state: present
    - name: Create firewall
      register: firewall
      # https://docs.ansible.com/ansible/latest/collections/hetzner/hcloud/firewall_module.html#ansible-collections-hetzner-hcloud-firewall-module
      # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_loops.html
      hetzner.hcloud.firewall:
        name: my-firewall
        labels: {
          firewall: ssh
        }
        rules:
          - description: allow icmp from everywhere
            direction: in
            protocol: icmp
            source_ips:
              - 0.0.0.0/0
              - ::/0
          - description: allow ssh from everywhere
            direction: in
            protocol: tcp
            port: 22
            source_ips:
              - 0.0.0.0/0
              - ::/0
        state: present
    - name: Create docker host
      # https://docs.ansible.com/ansible/latest/collections/hetzner/hcloud/server_module.html#ansible-collections-hetzner-hcloud-server-module
      # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_loops.html
      hetzner.hcloud.server:
        name: "{{ item.name }}"
        server_type: "{{ item.type }}"
        image: docker-ce
        location: "{{ item.location }}"
        ssh_keys:
          - my-ssh-key
        firewalls:
          - "{{ firewall['hcloud_firewall']['id'] }}"
        state: started
      loop: "{{ servers }}"
